spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food_map
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server.port: 8080

